# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: A propos de nous
    url: https://landis-hub-quebec.github.io/#a-propos
    weight: 10
  - name: Nous rejoindre
    url: https://landis-hub-quebec.github.io/#nous-rejoindre
    weight: 20
  - name: Contact
    url: https://landis-hub-quebec.github.io/#contact
    weight: 60
